<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>oj</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		 /\*\*(?!\*)
		|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
		|^@(implementation)\b
	</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}|^@end\b</string>
	<key>keyEquivalent</key>
	<string>^~O</string>
	<key>name</key>
	<string>oj</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*@(class)\b</string>
			<key>name</key>
			<string>keyword.control.forward.js.oj</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((@)(implementation))\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*([A-Za-z_][A-Za-z0-9_]*)|\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\))?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.implementation.declaration.js.oj</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.js.oj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.js.oj</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.js.oj</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.js.oj</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.category.js.oj</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.scope.implementation.js.oj</string>
			<key>end</key>
			<string>((@)end)\b</string>
			<key>name</key>
			<string>meta.implementation.js.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#implementation_innards</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\bid\b(\s|\n)?</string>
			<key>name</key>
			<string>storage.type.id.js.oj</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\W(BOOL|SEL|id|Class)\W</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.js.oj</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>((@)selector)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.js.oj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.js.oj</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.js.oj</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.selector.method-name.js.oj</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.js.oj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.selector.js.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.js.oj</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:[a-zA-Z_:][\w]*)+</string>
					<key>name</key>
					<string>entity.name.selector.name-of-parameter.js.oj</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(YES|NO|Nil|nil|BOOL|SEL|id|Class)\b</string>
			<key>name</key>
			<string>keyword.js.oj</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bracketed_content</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pragma-mark</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special_variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bracketed_content</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.js.oj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.js.oj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.bracketed.js.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\w)(?&lt;=[\w\])"] )([A-Za-z_][A-Za-z0-9_]*(?:(?=:)|(?=\])))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.js.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\])</string>
					<key>name</key>
					<string>meta.function-call.js.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.name-of-parameter.js.oj</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.arguments.js.oj</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b([A-Za-z_][A-Za-z0-9_]*)(:)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bracketed_content</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ivar-in-method</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.js.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.js.oj</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.js.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.js.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&gt;\\\s*\n)</string>
							<key>name</key>
							<string>punctuation.separator.continuation.js.oj</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>implementation_innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method_super</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instance_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>interface_innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>ivar-in-method</key>
		<dict>
			<key>match</key>
            <string>[^"'0-9A-Za-z_](_.*?)\W</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>variable.language.ivar</string>
                </dict>
            </dict>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>^(-|\+)\s*</string>
			<key>end</key>
			<string>(?=\{|#)|;</string>
			<key>name</key>
			<string>meta.method.js.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.js.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.js.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*([A-Za-z_][A-Za-z0-9_]*\b)</string>
					<key>contentName</key>
					<string>meta.return-type.js.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_][A-Za-z0-9_]*(?=:)</string>
					<key>name</key>
					<string>entity.name.function.name-of-parameter.js.oj</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((:))\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.name-of-parameter.js.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.js.oj</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.js.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*([A-Za-z_][A-Za-z0-9_]*\b)?</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.js.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.method.js.oj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.argument-type.js.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>method_super</key>
		<dict>
			<key>begin</key>
			<string>^(?=-|\+)</string>
			<key>end</key>
			<string>(?&lt;=^\})|(?=#)|(?&lt;=^[\-+])</string>
			<key>name</key>
			<string>meta.method-with-body.js.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ivar-in-method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>pragma-mark</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.js.oj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.preprocessor.pragma.js.oj</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.pragma-mark.js.oj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(//#\s*(pragma\s+mark)\s+(.*))</string>
			<key>name</key>
			<string>meta.section</string>
		</dict>
		<key>special_variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(self|super)\b</string>
					<key>name</key>
					<string>variable.language.js.oj</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.oj</string>
	<key>uuid</key>
	<string>58D4B98A-2110-423E-9C80-CC9E202816E7</string>
</dict>
</plist>
