<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>oj</string>
	</array>
	<key>name</key>
	<string>oj</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>((@)(implementation))\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*([A-Za-z][A-Za-z0-9]*))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.oj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.oj</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.oj</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.oj</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.scope.implementation.oj</string>
			<key>end</key>
			<string>((@)end)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.oj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.implementation.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#implementation_innards</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BOOL|SEL|id|Class|instancetype)\b</string>
			<key>name</key>
			<string>storage.type.oj</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(YES|NO|Nil|nil|self|super)\b</string>
			<key>name</key>
			<string>keyword.oj</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@)(enum|const)\b</string>
			<key>name</key>
			<string>keyword.oj</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.oj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@)(class)\b</string>
			<key>name</key>
			<string>storage.type.oj</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((@)selector)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.oj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.oj</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.oj</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.selector.method-name.oj</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.oj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.selector.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.oj</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:[a-zA-Z_:][\w]*)+</string>
					<key>name</key>
					<string>support.function.any-method.name-of-parameter.oj</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#pragma-mark</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bracketed_content</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ivar</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.block.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_innards</string>
				</dict>
			</array>
		</dict>
		<key>block_innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bracketed_content</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.oj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.oj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.bracketed.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\w)(?&lt;=[\w\])"] )(\w+(?:(:)|(?=\])))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.any-method.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\])</string>
					<key>name</key>
					<string>meta.function-call.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.arguments.oj</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b\w+(:)</string>
							<key>name</key>
							<string>support.function.any-method.name-of-parameter.oj</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#special_variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.js</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.js</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.js</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.js</string>
				</dict>
			</array>
		</dict>
		<key>implementation_innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property_directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method_with_body</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>ivar</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.ivar.oj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(_.*?)\b</string>
		</dict>
		<key>method_definition</key>
		<dict>
			<key>begin</key>
			<string>^(-|\+)\s*</string>
			<key>end</key>
			<string>(?=\{|#)|;</string>
			<key>name</key>
			<string>meta.function.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.begin.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*(\w+\b)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.end.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.oj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.return-type.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\w+(?=:)</string>
					<key>name</key>
					<string>entity.name.function.name-of-parameter.oj</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((:))\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.name-of-parameter.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.oj</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.begin.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*(\w+\b)?</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.end.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.oj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.argument-type.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>method_with_body</key>
		<dict>
			<key>begin</key>
			<string>^(?=-|\+)</string>
			<key>end</key>
			<string>(?&lt;=\})|(?=#)</string>
			<key>name</key>
			<string>meta.function-with-body.oj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method_definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>pragma-mark</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.oj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.pragma.oj</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.pragma-mark.oj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\/\/#\s*(pragma\s+mark)\s+(.*))</string>
			<key>name</key>
			<string>meta.section</string>
		</dict>
		<key>properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>((@)property)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.property.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.oj</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.oj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.oj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.property-with-attributes.oj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(getter|setter|readonly|readwrite|assign|retain|copy|nonatomic|strong|weak)\b</string>
							<key>name</key>
							<string>keyword.other.property.attribute</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.property.oj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.oj</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((@)property)\b</string>
					<key>name</key>
					<string>meta.property.oj</string>
				</dict>
			</array>
		</dict>
		<key>property_directive</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.oj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@)(dynamic|synthesize)\b</string>
			<key>name</key>
			<string>keyword.other.property.directive.oj</string>
		</dict>
		<key>special_variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(self)\b</string>
					<key>name</key>
					<string>variable.language.self.oj</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(super)\b</string>
					<key>name</key>
					<string>variable.language.super.oj</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.oj</string>
	<key>uuid</key>
	<string>04EBE779-56D9-4C63-B39A-E60AAB6DD44E</string>
</dict>
</plist>
